AppWithIdentity/AppWithIdentity/Controllers/ContactListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppWithIdentity.Controllers
{
    [Authorize]
    public class ContactListController : Controller
    {
        [Authorize(Roles = "admin,operator")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public IActionResult Edit()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public IActionResult Delete()
        {
            return View();
        }
    }
}

AppWithIdentity/AppWithIdentity/Views/ContactList/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>This will delete the contact</h1>

AppWithIdentity/AppWithIdentity/Views/ContactList/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>This will edit the contact</h1>

AppWithIdentity/AppWithIdentity/Views/ContactList/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>This is a private page</h1>
<table border="1" cellpadding="5">
    <thead>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Phone</td>
            @if (User.IsInRole("admin"))
            {
            <td>Actions</td>
            }
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Contact 1</td>
            <td>contact1@accountsapp.com</td>
            <td>122334343</td>
            @if (User.IsInRole("admin"))
            {
            <td>
                <a asp-controller="ContactList" asp-action="Edit">Edit</a>
                <span>&nbsp; | &nbsp;</span>
                <a asp-controller="ContactList" asp-action="Delete">Delete</a>
                    
            </td>
            }
            </tr>
        <tr>
            <td>Contact 2</td>
            <td>contact2@accountsapp.com</td>
            <td>45345345343</td>
            @if (User.IsInRole("admin"))
            {
            <td>
                <a asp-controller="ContactList" asp-action="Edit">Edit</a>
                <span>&nbsp; | &nbsp;</span>
                <a asp-controller="ContactList" asp-action="Delete">Delete</a>
                    
            </td>
            }
            </tr>
    </tbody>
</table>